version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Contents of imagedefinitions.json:"
      - cat imagedefinitions.json
      - echo "Creating complete appspec.yml for CodeDeploy..."
      - |
        cat > appspec.yml << 'EOF'
        version: 0.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: <TASK_DEFINITION>
                LoadBalancerInfo:
                  ContainerName: "app"
                  ContainerPort: 8080
                PlatformVersion: "LATEST"
        EOF
      - echo "Contents of appspec.yml:"
      - cat appspec.yml
      - echo "Build completed successfully"
      - echo "Current directory:"
      - pwd
      - echo "Directory contents:"
      - ls -la
      - echo "Verifying imagedefinitions.json exists:"
      - test -f imagedefinitions.json && echo "File exists" || echo "File missing"
      - echo "File size and permissions:"
      - ls -la imagedefinitions.json || echo "File not found"
      - echo "Working directory for artifacts:"
      - echo $CODEBUILD_SRC_DIR

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
  base-directory: .
  name: build-artifacts
